//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAcadmy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cour()
        {
            this.data_of_student = new HashSet<data_of_student>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int teacher { get; set; }
        public System.DateTime datestart { get; set; }
        public string imag { get; set; }
        public int dep { get; set; }
        public string contentcourse { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<data_of_student> data_of_student { get; set; }
        public virtual Department Department { get; set; }
        public virtual trainer trainer { get; set; }
    }
}
