//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAcadmy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class data_of_student
    {
        public int id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string gender { get; set; }
        public string Adress { get; set; }
        public string gamil { get; set; }
        public string telephone { get; set; }
        public Nullable<int> id_courese { get; set; }
        public string id_student { get; set; }
    
        public virtual cour cour { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
